### ISSUE TITLE
[SEO] Pre-process images for badges

### ISSUE THREAD

**Issue by AucT** [jetthoughts/jetthoughts.github.io#107]
![Image](https://github.com/user-attachments/assets/77e95963-9b45-4edd-a3b4-1e7ff039719d)

1. Use svg versions if there is version
2. Pre-process: set explicit width and height and use webp format
![Image](https://github.com/user-attachments/assets/d7ffe907-069f-4122-8351-20101876edad)

**Comment by pftg** [comment]
@AucT give me a link to the current code where I can find it. There are no fingerprints per image

**Comment by pftg** [comment]
Fixed in master
