### ISSUE TITLE
[SEO] Deffer offscreen images on home

### ISSUE THREAD

**Issue by AucT** [jetthoughts/jetthoughts.github.io#111]
For jetthoughts.com https://pagespeed.web.dev/analysis/https-jetthoughts-com/tb932lzlo3?form_factor=mobile

![Image](https://github.com/user-attachments/assets/e452cffc-106f-40af-b521-dede8afdc27d)

**Comment by AucT** [comment]
Few examples

![Image](https://github.com/user-attachments/assets/01bcd949-ccd2-4a4c-af26-6056dfd4ff3e)
![Image](https://github.com/user-attachments/assets/00f2601b-5a7a-49bd-ba28-ee31f91184d4)

**Comment by AucT** [comment]
`When it comes to CSS background images, there is currently no way to directly apply the fetchpriority attribute to them. This is because background images are typically set in CSS and do not have an associated HTML element that can utilize the fetchpriority attribute.`

**Comment by pftg** [comment]
@AucT please check https://web.dev/ or chatgpt how to make it work for CSS

**Comment by pftg** [comment]
@AucT, can we defer the CSS that has this image? Or replace with gradient match colors as much as possible?

**Comment by AucT** [comment]
nope
