### ISSUE TITLE
Use pre-processed images for home page only

### ISSUE THREAD

**Issue by AucT** [jetthoughts/jetthoughts.github.io#113]
Parent: #108

We should clean up images on home pages to process all files in the correct sizes and formats. There are no duplications, etc.

Make sure that 
![Accelerate   Achieve Your Product Vision 2024-09-13 11-50-53](https://github.com/user-attachments/assets/4efbc9f1-31f5-4a1a-ba20-562238423165)

**Comment by pftg** [comment]
@AucT, make sure that there are no duplications of using SVG icons, too.

And that files are processed and converted into appropriate sizes, like 
![Accelerate   Achieve Your Product Vision 2024-09-15 17-21-16](https://github.com/user-attachments/assets/090344b9-050e-402b-8eca-bfd21ba846e0)

**Comment by pftg** [comment]
- [x] Remove leftover `/wp-content/uploads/2022/10/build-faster-scale-smarter.webp`
- [ ] Use pre-processed assets for CSS files: converted to webp, fingerprinted, resized
- [x] Update responsive params for build-faster-scale-smarter to fill in 360px width
- [x] Extract SVG inlines to separate files
- [x] Use pre-processed images in meta tags
- [ ] Pre-processes: ` <link rel="preload" as="image" href='{{ absURL "wp-content/uploads/2022/10/white-border-background.webp" }}'>`

**Comment by AucT** [comment]
![6AMObym2yE](https://github.com/user-attachments/assets/b9f73733-3297-4c52-9e2c-502c10682415)

> Use pre-processed assets for CSS files: converted to webp, fingerprinted, resized

after css will be normalized

**Comment by pftg** [comment]
> ![6AMObym2yE](https://private-user-images.githubusercontent.com/2072488/367799816-b9f73733-3297-4c52-9e2c-502c10682415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDU3MDIsIm5iZiI6MTcyNjUwNTQwMiwicGF0aCI6Ii8yMDcyNDg4LzM2Nzc5OTgxNi1iOWY3MzczMy0zMjk3LTRjNTItOWUyYy01MDJjMTA2ODI0MTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTZUMTY1MDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGE4NDhiMTcyNzZjYjAwMWY2MmE2NmNhMDhlYmYxZjllNDYwNWE4NjgzNjk2MGRmNGJhMjk2YWNhNzAzZDRhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I_ooa0bbbpcSjK6bvSPfgKAyWvDPdDDYdxjjGxwWZbI)
> 
> > Use pre-processed assets for CSS files: converted to webp, fingerprinted, resized
> 
> after css will be normalized

@AucT please create sample small css with that background as example. We are not going to normalize css, we are going to delete it soon. But for now we need to fix this at least for homepage, which has been normalized already.

**Comment by pftg** [comment]
@AucT left one image 
![Accelerate   Achieve Your Product Vision 2024-09-17 13-31-19](https://github.com/user-attachments/assets/3a136b26-16c1-40e6-9f13-ca024fb63b71)
 
When can we close this issue? What blocks you?

**Comment by pftg** [comment]
Fixed for master: ![Image](https://github.com/user-attachments/assets/dd76a705-6591-4f1c-b683-62c3a0809db1)
