### ISSUE TITLE
add devto_url

### ISSUE THREAD

**Issue by AucT** [jetthoughts/jetthoughts.github.io#176]
in order to throw a link to dev.to, you need to throw something like this in the post variable

`devto_url: https://dev.to/jetthoughts/jetthoughts-receives-first-review-on-clutchco-thank-you-3i48`  
and also: if it is not difficult, it would be cool for the cron to go through and create a file like: comment_cont.json or something like that and had a structure:

```
[{
ID: 127
hugo_slug: "some-slug",
devto_slug: "some_slug",
comments_count: 3
}]
```

something from the search engines, so that later in hugo you can make a link  
`Comments (3)`
And in general, throwing links to comments on dev.to is a kind of activity. After all, this is someone else's site

**Comment by pftg** [comment]
@dgorodnichy please unassign yourself when it's ready fore verification

**Comment by dgorodnichy** [comment]
@AucT , Ready for verify. You can check by looking at the updated articles in this PR. Now they all contain links to dev.to
