### ISSUE TITLE
[BUG] fix technologies css for mobile

### ISSUE THREAD

**Issue by AucT** [jetthoughts/jetthoughts.github.io#178]
![Image](https://github.com/user-attachments/assets/af82a149-0df8-41f0-997b-24561ad7f420)

**Comment by AucT** [comment]
pushed to master

![Image](https://github.com/user-attachments/assets/546a4bbe-06dc-4ee3-8aef-888bc45b92e5)

**Comment by pftg** [comment]
@AucT let's have max 2-3 in a row for small screens and increase space between icons

**Comment by AucT** [comment]
@pftg check again, it should be ok (4 per row but with fixed text align) from yesterday or 2 days ago.
