### ISSUE TITLE
[REFACT] Remove usage of the absolute url generation

### ISSUE THREAD

**Issue by AucT** [jetthoughts/jetthoughts.github.io#182]
To test the app, we have to create a site with a specific port and URL. This limits flexibility, as we have to build separate sites for each parallel test. It's best to avoid using absolute URL generation and instead use relative paths.

**Comment by pftg** [comment]
There are some leftovers 
![jetthoughts github io – footer html 2024-10-23 09-31-25](https://github.com/user-attachments/assets/75a56e6c-b158-4610-a492-d428f93fe85c)
