### ISSUE TITLE
[BUG] could not sync one post

### ISSUE THREAD

**Issue by dgorodnichy** [jetthoughts/jetthoughts.github.io#202]
https://github.com/jetthoughts/jetthoughts.github.io/pull/175#pullrequestreview-2429493275

![image](https://github.com/user-attachments/assets/9da72b55-37e9-4f6d-9569-113c948d6509)

**Comment by dgorodnichy** [comment]
Need to clarification.

**Comment by pftg** [comment]
@dgorodnichy updated

**Comment by dgorodnichy** [comment]
https://dev.to/jetthoughts/the-trial-period-for-staff-augmentation-in-jetthoughts-1h5c
https://dev.to/jetthoughts/the-trial-period-for-staff-augmentation-in-jetthoughts-eff

We had duplicates. I fixed it.
