### ISSUE TITLE
Generate meta tags like on ThoughtBot

### ISSUE THREAD

**Issue by AucT** [jetthoughts/jetthoughts.github.io#40]
Per each post, we must provide SEO and Social Networks meta tags.

Some examples: `view-source:https://thoughtbot.com/blog/wrap-your-dependencies`

![Image](https://github.com/user-attachments/assets/d518c2ff-a112-4ec1-a1ac-4d0e5dda7af2)

**Comment by dgorodnichy** [comment]
@AucT ,
На ThoughtBot Я для твиттера вижу больше тегов
Отсутствуют:
- URL
- title
- description
- image

**Comment by AucT** [comment]
added twitter:title

**Comment by pftg** [comment]
@AucT please convert this to PR https://medium.com/notes-and-tips-in-full-stack-development/convert-github-issue-to-pull-request-c624834835d8

**Comment by pftg** [comment]
@AucT please convert to PR
