### ISSUE TITLE
All images in blog and on site should have different sources

### ISSUE THREAD

**Issue by AucT** [jetthoughts/jetthoughts.github.io#42]
We need to generate different types of images and sizes per device for performance. And provide them as sources https://www.w3schools.com/tags/tag_picture.asp#:~:text=The%20element%20contains%20two,specified%20in%20the%20srcset%20attribute).

- [ ] Find the best image types and sizes that we need to generate  on the build stage
- [x] Setup using responsive auto-generating images for the site
- [x] Setup using responsive auto-generating images for the blog

### References:

- https://discourse.gohugo.io/t/using-responsive-images-with-hugo/37524

**Comment by pftg** [comment]
@AucT please convert this issue into PR to find faster related code changes `hub pull-request -i 42` or learn about how to link issue with PR
