### ISSUE TITLE
[cls] Delay GA.js to be loaded after page has been rendered

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jetthoughts.github.io#49]
We must find a way to remove delayed loading by ga and GTM. It's ok if they are loaded later. We count only page loads.

![Image](https://github.com/user-attachments/assets/6498a072-99d4-4866-9fc8-d5589780a0cb)

## Reference:
* https://constantsolutions.dk/2020/06/delay-loading-of-google-analytics-google-tag-manager-script-for-better-pagespeed-score-and-initial-load/

**Comment by AucT** [comment]
@pftg give me the latest ga code from google analytics

**Comment by pftg** [comment]
Fixed in master
