### ISSUE TITLE
[BUG] social networks do not have image preview for posts

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jetthoughts.github.io#54]
There are no image previews for Twitter and Discord (you can use https://linkpreview.xyz/):

- ![Image](https://github.com/user-attachments/assets/2200e872-a509-4a3f-a0c2-eadeed3cdb64)
- ![Image](https://github.com/user-attachments/assets/eed92108-8ad3-4d1f-b14a-19d1ae6fe866)
- ![Image](https://github.com/user-attachments/assets/ef6f02e3-a0b5-46a1-a3dd-2241edd47590)

**Interesting but the list page is working:**

![Image](https://github.com/user-attachments/assets/e4bd6e6e-848c-469f-a77e-339a113cec72)

**Comment by AucT** [comment]
@pftg 
After changing to pageBundle this must works purrfect
This should be resolved.

I checked in facebook and twitter - works fine

**Comment by pftg** [comment]
@AucT does not work: 
![ X 2024-09-04 10-38-08](https://github.com/user-attachments/assets/7a279b03-bfa4-4d57-9b1d-c5ed09115a9f)

![Linkpreview - Check your website og image, meta tags, favicon, etc  2024-09-04 10-37-24](https://github.com/user-attachments/assets/5fe20d65-9523-44fe-adc3-9252cc663f9d)

**Comment by AucT** [comment]
@pftg works for me 

Maybe twitter / facebook has some pages in cache. For example this twitter cached https://jetthoughts.com/blog/working-with-llms-in-ruby-on-rails-simple-guide-llm/ and it for now doesn't display preview :(


![Image](https://github.com/user-attachments/assets/acf037df-21cd-4e22-be4b-2822abe51352)
![Image](https://github.com/user-attachments/assets/216c0ed4-4699-46e1-a5f1-63adcb7eb982)




![Image](https://github.com/user-attachments/assets/77bdaa5d-7dbb-450c-a589-23186273cf6e)

**Comment by AucT** [comment]
quick update:
maybe twitter simply check extension. [It has jpeg, but twitter only supports:](https://jetthoughts.com/blog/working-with-llms-in-ruby-on-rails-simple-guide-llm/)


```
Images must be less than 5MB in size. JPG, PNG, WEBP and GIF formats are supported.
```

**Comment by AucT** [comment]
quick update:
was troubleshooting https://jetthoughts.com/blog/working-with-llms-in-ruby-on-rails-simple-guide-llm/
so I used same image on my host, didn't worked, then cropped to 840x420 and used on different url, it worked, then tried again original image on different my host url and somehow twitter begin to create preview.

So I assume I need to give twitter good url then I can post cached like this https://jetthoughts.com/blog/working-with-llms-in-ruby-on-rails-simple-guide-llm/ and twitter somehow retrigger creating preview.

Very strange twitter behavior but it worked.

![zT6wGUcVed](https://github.com/user-attachments/assets/f57da73a-4abf-4a89-956a-f6c166470ccb)

**Comment by pftg** [comment]
@AucT please check this url https://jetthoughts.com/blog/deploying-ruby-on-rails-applications-with-kamal-devops-docker/

**Comment by pftg** [comment]
@AucT need to pre-process our cover images to make it work for twitter: 

https://developer.x.com/en/docs/x-for-websites/cards/overview/markup

![Image](https://github.com/user-attachments/assets/74fc8559-60b0-43f5-81dd-f04ba32ad0ec)

**Comment by pftg** [comment]
Fixed
