### ISSUE TITLE
[cls] Reduce dependency of redundant js and css for navbar

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jetthoughts.github.io#59]

**Comment by pftg** [comment]
@AucT please fix feedback from pr review

**Comment by dgorodnichy** [comment]
@AucT . How Can I verify this task?

**Comment by AucT** [comment]
@dgorodnichy check pull request https://github.com/jetthoughts/jetthoughts.github.io/pull/63

**Comment by pftg** [comment]
@andriyParashchuk will handle the last UI/UX change to look more like our original site.

**Comment by pftg** [comment]
@andriyParashchuk @AucT for site part we removed redundant js.

**Comment by dgorodnichy** [comment]
@AucT , I haven't seen any progress on this task for more than two days. Is there a blocker here? What are the steps to move this task forward?
I also don't see a PR for this task.

**Comment by AucT** [comment]
@dgorodnichy this task is assigned to @andriyParashchuk 

remember you closed my new-html-css-blog-list branch and PR
