### ISSUE TITLE
[REFACT] Use one template for all pages

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jetthoughts.github.io#87]
1. Extract the standard layout for all pages:
Please ensure all pages have the same layout, including meta, header, and footer. Each page should override the content block and allow the extension of CSS and JS loading.
  * Extract the top navigation bar partial
  * Extract include CSS and JS
  * Allow to customize CSS and JS per page
3. Eventually fix bug with broken footer: footer is expecting 4 opened div but we have `article`

**Comment by AucT** [comment]
```
Extract include CSS and JS
Allow to customize CSS and JS per page
```

Extraction will create such mess. In baseof I copy header, footer and add blocks for per page css links, and inside page use that code.
 If you like this, I can continue.

![0PmcLKwYWj](https://github.com/user-attachments/assets/6bc75b37-f5e6-4080-88f8-91bfac1dcfec)
![m8lSGENKJ4](https://github.com/user-attachments/assets/b458b595-7ebe-459e-a9d7-e395cc80916e)

**Comment by pftg** [comment]
@AucT yep looks good

**Comment by pftg** [comment]
@dgorodnichy please review and merge
