### ISSUE TITLE
[REFACT] Remove usage from the old image locations on dev.to

### ISSUE THREAD

**Issue by AucT** [jetthoughts/jetthoughts.github.io#96]
We moved our images to new locations and need to use them for `dev.to`. We need to update `dev.to` posts with new locations. And delete legacy files.

**Comment by pftg** [comment]
@dgorodnichy please handle this

**Comment by dgorodnichy** [comment]
Done. Already on production

**Comment by pftg** [comment]
@dgorodnichy can we delete them? Should we create redirect rules for cached posts?

**Comment by dgorodnichy** [comment]
@pftg Old Images are already deleted.
